# Generated by Django 5.1.2 on 2024-11-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undecided_voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingrun',
            name='date_range_end',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapingrun',
            name='date_range_start',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
