# Generated by Django 5.1.2 on 2024-11-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undecided_voters', '0002_scrapingrun_date_range_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapingrun',
            name='date_range_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scrapingrun',
            name='date_range_start',
            field=models.DateTimeField(null=True),
        ),
    ]
