# Generated by Django 5.1.2 on 2024-11-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undecided_voters', '0003_alter_scrapingrun_date_range_end_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyanalysis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rawpost',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scrapingrun',
            name='source',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('newsapi', 'News API'), ('all', 'All Sources')], default='twitter', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyanalysis',
            name='source',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('newsapi', 'News API'), ('all', 'All Sources')], default='twitter', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rawpost',
            name='source',
            field=models.CharField(choices=[('twitter', 'Twitter'), ('newsapi', 'News API'), ('all', 'All Sources')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyanalysis',
            unique_together={('week_start', 'week_end', 'source')},
        ),
    ]
